site_name: Data tensors in RDF
site_url: https://rdf-tensor.github.io/jena-datatensor/

repo_url: 'https://github.com/RDF-tensor/jena-datatensor'
repo_name: RDF-tensor/jena-datatensor
edit_uri: edit/main/docs/

plugins:
  - search
  - include-markdown

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  custom_dir: overrides
  features:
    # Behave like an SPA
    - navigation.instant
    - navigation.instant.progress
    # Update anchors in the address bar
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/RDF-tensor/jena-datatensor'
      name: GitHub

nav:
  - Home – specification: 'index.md'
  - Ontology:
    - RDF datatypes: 'ontology/datatypes.md'
    - SPARQL functions: 'ontology/functions.md'
    - SPARQL aggregates: 'ontology/aggregates.md'
  - Paper: 'https://rdf-tensor.github.io/jena-datatensor' # TODO
  - Jena implementation: 'https://github.com/RDF-tensor/jena-datatensor/tree/main/jena-datatensor'
  - Example dataset & queries: 'https://github.com/RDF-tensor/jena-datatensor/tree/main/example_dataset_and_queries'
